import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/Button";
import { Form } from "../components/Form";
import { Header } from "../components/Header";
import { SearchInput } from "../components/Search";
import { useSearchStore } from "../store/SearchStore";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {
    setInputIsFocus,
    inputIsFocus,
    inputValue,
    setInputValue,
    setClearInputValue,
  } = useSearchStore();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 dark:bg-gray-800">
        <header className="p-1 text-gray-600 dark:text-gray-200">
          <h1 className="text-3xl">Nasa Next App</h1>
        </header>
        <Form>
          <SearchInput
            value={inputValue}
            setClearInputValue={setClearInputValue}
            inputIsFocus={inputIsFocus}
            setInputIsFocus={setInputIsFocus}
            setInputValue={setInputValue}
          />
        </Form>
      </main>
    </>
  );
};

export default Home;
