import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { PostBody } from "../../components/PostBody";
import type { Collection, NasaApi } from "../../types";
import { dateFormatter } from "../../utils/helpers/dateFormatter";
import { trpc } from "../../utils/trpc";
import { useEffect, useState } from "react";
export default function Title({ }) {
  const router = useRouter();
  const [pageIsLoaded, setPageIsLoaded] = useState(false);
  const { data, isLoading, isError } = trpc.nasaApi.getById.useQuery({
    index: Number(router.query.index),
    q: router?.query.q as string,
  });
  useEffect(() => {
    setPageIsLoaded(true);
  }, []);

  if (!pageIsLoaded) return null;

  return (
    <>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 dark:bg-gray-800">
        {isError && <p>Data Not Found</p>}
        {isLoading && <p>Loading...</p>}

        {data && <PostBody {...data?.data} image={data.image} />}
      </main>
    </>
  );
}
